apiVersion: apps/v1
kind: Deployment
metadata:
  name: argodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argodemo
  template:
    metadata:
      labels:
        app: argodemo
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always